# Generated by Django 3.0.6 on 2020-05-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcodr',
            new_name='zipcode',
        ),
    ]
